NonStupidDigestAssets.whitelist = [
  'application.css',
  'application.js',
  'mail.png',
  'placemark.png',
  'player.swf',
  'tusur_logotype.png',
  'video-640x360.txt',
  /FontAwesome*/,
  /OfficinaSerifBoldC*/,
  /OfficinaSerifBookSCC*/,
  /PTSans*/,
  /ckeditor\/.*/,
  /bootstrap\/glyphicons-halflings-regular*/,
  /fontawesome-webfont*/,
]
