require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("jquery-ui/ui/widgets/autocomplete")
require("commons/users_autocomplete")
